#***********************************************************************************************************************
# cargo make tasks to build the example for the Raspberry Pi
#***********************************************************************************************************************
[env.development]
CC = "aarch64-none-elf-gcc"
AR = "aarch64-none-elf-ar"
OCOPY = "aarch64-none-elf-objcopy"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C target-cpu=cortex-a53 -C target-feature=+strict-align,+a53,+fp-armv8,+neon -C link-arg=-T./link64.ld"
QEMUMACHINE = "raspi3"
QEMUCMD = "qemu-system-aarch64"

[env.pipeline]
CC = "aarch64-linux-gnu-gcc"
AR = "aarch64-linux-gnu-ar"
OCOPY = "aarch64-linux-gnu-objcopy"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C target-cpu=cortex-a53 -C target-feature=+strict-align,+a53,+fp-armv8,+neon -C link-arg=-T./link64.ld"
QEMUMACHINE = "raspi3b"
QEMUCMD = "./qemu/bin/qemu-system-aarch64"

[tasks.build]
command = "cargo"
args = ["build", "--release", "--features", "${FEATURES}"]

[tasks.clippy]
env = { FEATURES = "" }
command = "cargo"
args = ["clippy", "--features", "${FEATURES}"]

[tasks.doc]
env = { FEATURES = "" }
command = "cargo"
args = ["doc", "--features", "${FEATURES}", "--open"]

[tasks.pi3]
env = { FEATURES = "" }
run_task = "build"

[tasks.clean]
command = "cargo"
args = ["clean"]


[tasks.test]
command = "cargo"
args = ["test", "--tests", "--features", "multicore"]

[tasks.qemu-test-objcopy]
command = "${OCOPY}"
args = ["-O",  "binary",  "${CARGO_MAKE_TASK_ARGS}", "./target/kernel8.img"]

[tasks.qemu-test]
command = "${QEMUCMD}"
args = [
    "-semihosting", "-nographic", "-M", "${QEMUMACHINE}", "-kernel", "./target/kernel8.img", "-serial", "null", "-serial", "mon:stdio", "-d", "int,mmu", "-D", "qemu.log"
]
dependencies = [
    "qemu-test-objcopy"
]