#***********************************************************************************************************************
# cargo make tasks to build the example for the Raspberry Pi
#***********************************************************************************************************************

# AARCH64 specific profile environment varialbles
[env.development]
CC = "aarch64-none-elf-gcc"
AR = "aarch64-none-elf-ar"
OCOPY = "aarch64-none-elf-objcopy"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53 -C link-arg=-nostartfiles -C link-arg=-T./link64.ld"
BUILD_TARGET = "aarch64-unknown-none"
QEMUMACHINE = "raspi3"
QEMUCMD = "qemu-system-aarch64"


# AARCH64 specific Travis CI env. variables. "aarch64-none-elf" is not available there as it seems
[env.travis]
CC = "aarch64-linux-gnu-gcc"
AR = "aarch64-linux-gnu-ar"
OCOPY = "aarch64-linux-gnu-objcopy"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53 -C link-arg=-nostartfiles -C link-arg=-T./link64.ld"
BUILD_TARGET = "aarch64-unknown-none"
QEMUMACHINE = "raspi3b"
QEMUCMD = "./qemu/bin/qemu-system-aarch64"

[tasks.xbuild]
command = "cargo"
args = ["xbuild", "--target", "${BUILD_TARGET}", "--release", "--features", "${FEATURES}"]

[tasks.pi3]
env = { FEATURES = "ruspiro_pi3" }
run_task = "xbuild"

[tasks.clippy]
env = { FEATURES = "ruspiro_pi3" }
command = "cargo"
args = ["clippy", "--target", "${BUILD_TARGET}", "--features", "${FEATURES}"]

[tasks.doc]
env = { FEATURES = "ruspiro_pi3" }
command = "cargo"
args = ["doc", "--target", "${BUILD_TARGET}", "--features", "${FEATURES}", "--open"]

[tasks.doctest]
env = { FEATURES = "ruspiro_pi3" }
command = "cargo"
args = ["test", "--doc", "--features", "${FEATURES}"]

[tasks.publish_dry]
env = { FEATURES = "ruspiro_pi3" }
command = "cargo"
args = ["publish", "--dry-run", "--target", "${BUILD_TARGET}", "--features", "${FEATURES}"]

[tasks.publish]
env = { FEATURES = "ruspiro_pi3" }
command = "cargo"
args = ["publish", "--token", "${CRATES_TOKEN}", "--allow-dirty", "--target", "${BUILD_TARGET}", "--features", "${FEATURES}"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.unittest]
env = { FEATURES = "ruspiro_pi3" }
command = "cargo"
args = ["xtest", "--target", "${BUILD_TARGET}", "--tests", "--features", "${FEATURES}"]

[tasks.qemu-test-objcopy]
command = "${OCOPY}"
args = ["-O",  "binary",  "${CARGO_MAKE_TASK_ARGS}", "./target/kernel8.img"]

[tasks.qemu-test]
command = "${QEMUCMD}"
args = [
    "-semihosting", "-nographic", "-M", "${QEMUMACHINE}", "-kernel", "./target/kernel8.img", "-serial", "null", "-serial", "mon:stdio"
]
dependencies = [
    "qemu-test-objcopy"
]